esphome:
  name: bulb-one
  platform: ESP8266
  board: esp01_1m
  on_boot:
      priority: 750
      then:
        - light.turn_on:
            id: bulb_one
            color_temperature: 3300K
            white: 40%

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.68.21
    gateway: 192.168.68.1
    subnet: 255.255.255.0


# Enable Home Assistant API
api:
ota:
logger:
  level: DEBUG

# Define output pins
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14

# Define a light entity
light:
  - platform: rgbww
    name: bulb_one
    id: bulb_one
    gamma_correct: 2.8
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2700 K

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
